# ip package

name: ip
parent: default

matches:
  - trigger: ":ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo $(dig +short myip.opendns.com @resolver1.opendns.com)"
